---
title: "COVID-19 Deaths"
author: "[Jim Tyhurst, Ph.D.](https://www.jimtyhurst.com/)  "
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    hard_line_breaks: FALSE
  html_document:
    toc: true
    code_folding: hide
numbersections: true
vignette: >
  %\VignetteIndexEntry{COVID19_Deaths}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

[Source code](./covid19_deaths.Rmd).

## tl;dr

```{r read_deaths, echo = FALSE, message = FALSE}
library(covid19)
library(dplyr)
library(lubridate)
library(ggplot2)

deaths <- read_deaths_jhu_csse()
```

Plots cumulative number of confirmed cases for a few selected countries. It is easy to tell by the shape of the curve whether the daily number of cases are increasing vs countries where the rate of deaths has decreased.

```{r total_by_country_summary, echo = FALSE, message = FALSE}
deaths %>%
  dplyr::filter(country_region %in% c("Czechia", "China", "Korea, South", "Iran", "Italy", "Spain", "US")) %>% 
  dplyr::group_by(country_region, date) %>% 
  dplyr::summarize(country_total = sum(cumulative_total)) %>% 
  ggplot(aes(x = date, y = country_total, group = country_region, color = country_region)) +
    geom_point(na.rm = TRUE) +
    geom_line(aes(y = country_total), na.rm = TRUE)  + 
  theme(
    panel.grid.minor = element_line(color="grey60", size=0.5),
    panel.grid.major = element_line(color="grey40", size=0.5),
    panel.background = element_rect(fill="snow2")
  ) +
  ggtitle("Deaths for selected countries") +
  labs(x = "Date", y = "Cumulative Total", color = "Country")
```
